    sources:
      - Readexpro.glyphs
    familyName: "Readex Pro"
    buildOTF: False
    buildWebfont: False
    axisOrder:
#      - HEXP
      - wght
    # stat:
    #   - name: Hyper Expansion
    #     tag: HEXP
    #     values:
    #     - name: Deca
    #       value: 0
    #     - name: Exa
    #       value: 40
    #     - name: Giga
    #       value: 56
    #     - name: Mega
    #       value: 64
    #     - name: Peta
    #       value: 72
    #     - name: Tera
    #       value: 80
    #     - name: Zetta
    #       value: 100
    #   - name: Weight
    #     tag: wght
    #     values:
    #     - name: Thin
    #       value: 100
    #     - name: ExtraLight
    #       value: 200
    #     - name: Light
    #       value: 300
    #     - name: Regular
    #       value: 400
    #       linkedValue: 700
    #       flags: 2
    #     - name: Medium
    #       value: 500
    #     - name: SemiBold
    #       value: 600
    #     - name: Bold
    #       value: 700
    #     - name: ExtraBold
    #       value: 800
    #     - name: Black
    #       value: 900