name: alternative LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2     
        with:       
          root_file: "DBS - Dungeon Bell System.tex"
          working_directory: ./DBS
      - name: Upload pdf
        uses: actions/upload-artifact@v2
        with:
          working-directory: ./DBS
          name: "DBS - Dungeon Bell System"
          path: "DBS - Dungeon Bell System.pdf"  
