
name: Compila OBSSv2
on: [push,workflow_dispatch]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          root_file: "OBSSv2.tex"
          working_directory: ./OBSS
      - name: Upload pdf
        uses: actions/upload-artifact@v4
        with:
          name: "OBSS - Old Bell School System"
          path: "./OBSS/OBSSv2.pdf"       
