name: Delete old workflow runs automatic
on:
  schedule:
    - cron: '0 0 1,7,14,21 * *'
  workflow_dispatch:
    inputs:
      days:
        description: 'Number of days.'
        required: true
        default: 30

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.SECRETTOKEN }}
          repository: buzzqw/TUS
          retain_days: 30
          keep_minimum_runs: 30
