name: 'Build LaTex Document'
on: 
  push:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        name: Tectonic Cache
        with:
          path: ~/.cache/Tectonic
          key: ${{ runner.os }}-tectonic-${{ hashFiles('**/*.tex') }}
          restore-keys: |
           ${{ runner.os }}-tectonic-
      - uses: wtfjoke/setup-tectonic@v1
        with:
          github-token: ${{secrets.SECRETTOKEN}}
      - name: Run Tectonic
        run: tectonic "DBS - Dungeon Bell System.tex"
      - name: Upload pdf
        uses: actions/upload-artifact@v2
        with:
          name: "DBS - Dungeon Bell System"
          path: "DBS - Dungeon Bell System.pdf"
